### ISSUE TITLE
AutoCAD DWG R11/12 0x01fc-0x0228

### ISSUE THREAD

**Issue by leshasoft** [michal-josef-spacek/CAD-Format-DWG-AC1009#1]
The structure contains the continuation of the menu string/

          0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
    000180 B9 3F 00 00 00 00 00 00-00 00 00 00 00 00 01 00   .?..............
    000190 00 00 01 00 43 3A 5C 41-43 41 44 31 32 5C 53 55   ....C:\ACAD12\SU
    0001A0 50 50 00 00 00 00 00 00-00 F0 3F 00 00 00 00 00   PP........?.....
    0001B0 00 08 40 00 00 00 00 00-00 00 00 00 00 00 00 00   ..@.............
    0001C0 00 18 40 00 00 00 00 00-00 08 40 00 00 00 00 00   ..@.......@.....
    0001D0 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................
    0001E0 00 0C 40 00 00 00 00 00-00 0C 40 00 00 00 00 00   ..@.......@.....
    0001F0 00 00 00 00 00 00 00 00-00 01 00 00 4F 52 54 5C   ............ORT\
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
    000200 41 43 41 44 00 41 44 00-00 00 00 00 00 00 00 00   ACAD.AD.........
    000210 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................
    000220 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................
    000230 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ................
    000240 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 F0   ................
    000250 3F 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00   ?...............

**Comment by michal-josef-spacek** [comment]
@leshasoft You are great, thank you very much :-)

**Comment by michal-josef-spacek** [comment]
Fixed

**Comment by leshasoft** [comment]
Always happy :)
In header by offset 0x24 4 bytes of address second entities table,
by offset 0x28 2 bytes size of table.

**Comment by michal-josef-spacek** [comment]
@leshasoft Please, use another issue for another thing.
